anitab-org/vms

docs/Installation Guide.md

PR for the develop branch
https://github.com/systers/vms/issues/19

Repair link in documentation

---

vms/home/templates/home/home.html
vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html
vms/registration/views.py

The splitted PR https://github.com/systers/vms/pull/15
Issue https://github.com/systers/vms/issues/16

Display a simple notification to the users that they have registered

---

vms/job/services.py
vms/job/tests.py

Here are the new unit tests for job - https://github.com/systers/vms/commit/67c4b58703258665dc77d5bfcfe369f1d81d935a
Also, all the code is pep8 now - https://github.com/systers/vms/commit/ea18fec21e337c54974cddb63b8253c146f01679

New unit tests for job

---

vms/job/services.py
vms/job/tests.py

Issue https://github.com/systers/vms/issues/41
DRY - Could we use test fixtures for this goal? For example setUp() and tearDown()?

Refactor job unit tests

---

vms/event/services.py
vms/event/tests.py

Issue https://github.com/systers/vms/issues/42

Refactor event unit tests + PEP8

---

vms/registration/views.py

@vubo Please review this PR. It started as a simple fix on the print statement that wasn't Python 3 compliant. I ended with me cleaning up a number of style and PEP8 issues.
I ran across the print issue when I was working on getting coverage.py running locally.
Just +1 if you think it looks ok and I will merge.

Fix print statement for PY3 and PEP8 cleanup - Issue #50

---

vms/vms/urls.py

Fix spacing in urls.py refactor for Issue #54

---

vms/volunteer/services.py
vms/volunteer/tests.py

Here is a new PR (old PR is https://github.com/systers/vms/pull/47).

Unit tests for volunteer

---

vms/shift/services.py
vms/shift/tests.py

Here is PR with the rebased and squashed commit history (last PR: https://github.com/systers/vms/pull/43). 
It was also found and fixed a bug in the function generate_report.

Unit tests for shift

---

vms/vms/settings.py

`settings.py` refactor to reflect best practices and more maintainable style
@vubo please review when you have time. thanks.

Refactor setting.py for style and best practices Issue #54

---

vms/job/tests.py

Based on the https://github.com/systers/vms/pull/44#issuecomment-111878038

Fixed import in the job/tests.py

---

vms/event/templates/event/create.html
vms/job/templates/job/create.html
vms/shift/templates/shift/create.html
vms/vms/static/vms/jquery-custom/activate-datepicker.js

Datepicker for Create Event, Job, Shift. (instead https://github.com/systers/vms/pull/61)

Datepickers for admin (create job, event, shift)

---

vms/volunteer/forms.py
vms/volunteer/models.py

Fix the issue https://github.com/systers/vms/issues/40 + PEP8

Fix volunteer form + PEP8

---

vms/event/forms.py
vms/event/models.py
vms/event/templates/event/create.html
vms/event/templates/event/edit.html
vms/event/templates/event/list.html

https://github.com/systers/vms/issues/68
Add location (country, state, city, address, venue) that the event is being held at.

Location specification for Event

---

vms/administrator/models.py
vms/volunteer/models.py

Issue https://github.com/systers/vms/issues/48

Unique email field

---

vms/shift/templates/shift/edit_hours.html
vms/vms/static/vms/datetimepicker/bootstrap-datetimepicker.min.css
vms/vms/static/vms/datetimepicker/bootstrap-datetimepicker.min.js
vms/vms/static/vms/js/timepicker.js
vms/vms/templates/vms/base.html

Issue https://github.com/systers/vms/issues/60
For the timepicker I used http://tarruda.github.io/bootstrap-datetimepicker/
But I had to change it a little bit, because this timepicker is for the bootstrap 2 version and we have bootstrap-3.2.0.

Timepicker for shift/edit_hours

---

vms/shift/forms.py
vms/shift/models.py
vms/shift/templates/shift/create.html
vms/shift/templates/shift/edit.html

https://github.com/systers/vms/issues/68
Add location (country, state, city, address, venue) that the shift is being held at.

Add location for Shift

---

vms/vms/settings.py
vms/volunteer/views.py

Porting Python 2 code to Python 3. 
I am using Python 3.4 and Django 1.8.3 now.
https://github.com/systers/vms/issues/12

Python 2 to 3

---

vms/administrator/views.py
vms/event/views.py
vms/job/views.py
vms/organization/views.py
vms/shift/views.py
vms/vms/templates/vms/no_admin_rights.html
vms/volunteer/views.py

Configure access for volunteers (return forbidden code for each administrator functionality that a volunteer tries to access).
Pep8 views.py for event, shift, job, organization
https://github.com/systers/vms/issues/87

Configure access for administrator features

---

vms/shift/views.py

Issue: https://github.com/systers/vms/issues/35#issuecomment-124924370
I fixed it. We first check if its not a volunteer and then raise a 403.

Fix a bug: volunteer shifts access

---

vms/event/forms.py
vms/event/services.py
vms/event/templates/event/list_sign_up.html
vms/event/tests.py
vms/event/views.py

Issue https://github.com/systers/vms/issues/81
Add a calender / date range opportunity for the event search.
Volunteer can find all events for specific dates.

Search for the events that start from...to

---

vms/shift/services.py
vms/volunteer/forms.py
vms/volunteer/templates/volunteer/report.html
vms/volunteer/views.py

Issue https://github.com/systers/vms/issues/102
Improve report for volunteers: Add a data range instead of the date

Add date range for report

---

README.md

There's been lots of good work happening over the past few months :+1:
I wanted to update this README with a list of contributors and also to reorder and edit some of the content (i.e. mention Django and Python).
Please comment, make additions, or merge as is. Keep up the great work :cat:

Update README to reflect recent work #109

---

vms/shift/templates/shift/add_hours.html
vms/shift/templates/shift/add_hours_manager.html
vms/shift/templates/shift/create.html
vms/shift/templates/shift/edit.html
vms/shift/templates/shift/edit_hours_manager.html

Add timepicker for:
- add hours
- add hours manager
- create shift
- edit shift
- edit hours manager
Issue https://github.com/systers/vms/issues/76

Add timepicker everywhere

---

vms/event/models.py
vms/job/models.py
vms/organization/models.py
vms/shift/models.py

Closes https://github.com/systers/vms/issues/98
Adds the possibility to insert an apostrophe for many models.

Apostrophe for models

---

Vagrantfile

This PR addresses #117. Issue #49 contains an improved Vagrantfile. This version streamlines the file and was tested on older Windows machine with good results.

Edit Vagrantfile

---

.gitignore

Let's be kind to future developers and document the .gitignore file.
Closes #121

Clean up gitignore and document

---

vms/administrator/forms.py
vms/administrator/templates/administrator/report.html
vms/administrator/views.py
vms/shift/services.py

https://github.com/systers/vms/issues/103
Improve reports for admins: Add a drop down for Organization and Add a date range instead of the date.

Administrator report enhancement

---

vms/vms/templates/vms/base.html

Closes https://github.com/systers/vms/issues/126
Now there is the drop-down menu for small screens.

Fix menu for small screens

---

docs/Installation Guide.md

Added 2.5 and 2.6 to install Python and pip.

Update Installation Guide.md

---

docs/Installation Guide.md

Updated the installation guide to allow users to follow a set up when not using the VM.

Updated to installation guide

---

vms/vms/templates/vms/base.html

I maked the template no fluid as it was before. It looks also better this way :blush:

Make template no fluid

---

vms/vms/urls.py

Add url pattern to show start up page when user navigates to home page.

Fixed navigation to home page

---

docs/Installation Guide.md

Added the details for the login and password in the Installation Docs that is required to boot up the vagrant virtual machine.

Updated the VM login and password in Installation Docs

---

vms/event/tests.py
vms/job/tests.py

Add unit tests for remove empty events and jobs functions

---

vms/administrator/models.py
vms/registration/templates/registration/signup_administrator.html

Now the following numbers could also get accepted:
+42 555.123.4567
+1-(800)-123-4567
+7 555 1234567
+7(926)1234567
(926) 1234567
+79261234567
926 1234567
9261234567
1234567
123-4567
123-89-01
495 1234567
469 123 45 67
89261234567
8 (926) 1234567
926.123.4567
415-555-1234
650-555-2345
(416)555-3456
202 555 4567
4035555678
1 416 555 9292
Please review and suggest changes if something is wrong.
Fixed #129

phone-number validation

---

vms/shift/services.py

Simplified Shift Sign Up

---

vms/shift/services.py

Revert "Simplified Shift Sign Up"

---

docs/Installation Guide.md

Keeping #178 in mind, maybe the version specification should be changed (for now) so that contributors who are building the project on local machines do not run into errors.
Please review

Changing django version specification

---

docs/Installation Guide.md

Mention of password to access postgresql

---

vms/administrator/templates/administrator/report.html
vms/administrator/templates/administrator/settings.html

Add i18n tags in administrator templates

---

vms/authentication/templates/authentication/login.html

Add i18n tags in authentication templates

---

vms/event/templates/event/create.html
vms/event/templates/event/delete.html
vms/event/templates/event/delete_error.html
vms/event/templates/event/edit.html
vms/event/templates/event/list.html
vms/event/templates/event/list_sign_up.html

Add i18n tags in event templates

---

vms/home/templates/home/home.html

Add i18n tags in home templates

---

vms/job/templates/job/create.html
vms/job/templates/job/delete.html
vms/job/templates/job/delete_error.html
vms/job/templates/job/details.html
vms/job/templates/job/edit.html
vms/job/templates/job/list.html
vms/job/templates/job/list_sign_up.html

Add i18n tags in job templates

---

vms/organization/templates/organization/create.html
vms/organization/templates/organization/delete.html
vms/organization/templates/organization/delete_error.html
vms/organization/templates/organization/edit.html
vms/organization/templates/organization/list.html

Add i18n tags in organization templates

---

vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html

Add i18n tags in registration templates

---

vms/shift/templates/shift/add_hours.html
vms/shift/templates/shift/add_hours_manager.html
vms/shift/templates/shift/cancel_shift.html
vms/shift/templates/shift/clear_hours.html
vms/shift/templates/shift/clear_hours_manager.html
vms/shift/templates/shift/create.html
vms/shift/templates/shift/delete.html
vms/shift/templates/shift/delete_error.html
vms/shift/templates/shift/edit.html
vms/shift/templates/shift/edit_hours.html
vms/shift/templates/shift/edit_hours_manager.html
vms/shift/templates/shift/hours_list.html
vms/shift/templates/shift/list_jobs.html
vms/shift/templates/shift/list_shifts.html
vms/shift/templates/shift/list_shifts_sign_up.html
vms/shift/templates/shift/manage_volunteer_shifts.html
vms/shift/templates/shift/sign_up.html
vms/shift/templates/shift/sign_up_error.html
vms/shift/templates/shift/volunteer_search.html
vms/shift/templates/shift/volunteer_shifts.html

Add i18n tags in shift templates

---

vms/vms/templates/vms/base.html
vms/vms/templates/vms/no_admin_rights.html

Add i18n tags in vms templates

---

vms/volunteer/templates/volunteer/edit.html
vms/volunteer/templates/volunteer/profile.html
vms/volunteer/templates/volunteer/report.html
vms/volunteer/templates/volunteer/search.html

Add i18n tags in volunteer templates

---

vms/shift/views.py

Show error if end time before starttime in editing shift

---

vms/shift/views.py

Simplify Shift sign up

---

vms/event/templates/event/create.html
vms/event/templates/event/edit.html
vms/job/templates/job/create.html
vms/job/templates/job/edit.html
vms/shift/templates/shift/create.html
vms/shift/templates/shift/edit.html

Marked compulsory fields for events, jobs and shifts. (Separating out the changes while updating a previous PR)
Closes #251

Marking compulsory fields

---

vms/vms/settings.py

Adding the necessary settings to enable i18n

Enable i18n

---

vms/administrator/templates/administrator/report.html
vms/administrator/views.py

Previously when the admin was creating report, the event was expected to be filled in text box. Updates have been made, to show  a dropdown menu, so as to enhance the experience.
https://gyazo.com/01f25fcc86a78208bbc0878bce3b030a
Closes #240

Dropdown menu for events in report

---

vms/administrator/templates/administrator/report.html
vms/administrator/views.py

Reverts systers/vms#239
Reverting as the commit messages were not helpful. The committer will fix it and it will be remerged.

Revert "Dropdown menu for events in report"

---

vms/shift/views.py

No redirection to job list page if shifts are non empty

---

vms/vms/templates/vms/base.html

Added dropdown options for signed in users instead of separate links

---

vms/shift/templates/shift/edit.html

Added datepicker for edit shift

---

docs/Project Settings.md

There have been various changes in the settings file, which haven't been included in the documentation. This PR aims to update it.
Closes #285

Updated the project settings (docs) based on recent development

---

docs/Installation Guide.md

Update to installation guide with instructions for installing additional packages. Lower limit of Django Version has also been updated to 1.7

Updated installation guide

---

vms/shift/views.py

Checks for validity of logged hours both during logging hours and editing logged hours.
Fixes #226

Checking for logged hours to be between scheduled shift hours

---

vms/administrator/templates/administrator/report.html
vms/administrator/views.py

Created a dropdown menu for events in report.html to reduce confusion for the user.

 Dropdown menu for events for report generation

---

vms/volunteer/templates/volunteer/profile.html

The data is now neatly aligned and is more readable.
resolve #268

Volunteer profile data alignment using html tables

---

vms/administrator/admin.py
vms/event/admin.py
vms/job/admin.py
vms/organization/admin.py
vms/shift/admin.py
vms/volunteer/admin.py

Added Admin panel entry for all models

---

vms/event/templates/event/edit.html
vms/event/views.py

Start date later than today ( edit.html)

---

vms/vms/templates/vms/base.html

Migrating to About page from other pages

---

vms/administrator/templates/administrator/report.html
vms/administrator/views.py

When administrator generates report, the input for job is taken as text. Instead I have added a dropdown menu for jobs to avoid confusion.

Added dropdown option for job input when administrator generates report.

---

vms/home/urls.py
vms/home/views.py

Migrated index function in home application to Template view.

Migrated home application from FBV to CBV

---

vms/administrator/tests/test_report.py
vms/home/tests/test_functional.py
vms/volunteer/tests/test_volunteerProfile.py
vms/volunteer/tests/test_volunteerReport.py

After merging this PR and once travis ci is added, the build is not expected to fail for the develop branch.
First commit is to comment out errors/failures which I could get on the local while the second commit is to fix 2 extra errors which seemed to be occurring only on travis. I did not get these errors on local.
The tests commented out have been documented and will be added back again once the respective bugs are fixed.
On running test command now, 150 total (unit + functional/UI) tests should be run. 
[Build](https://travis-ci.org/smarshy/vms/builds/135995485).
Please review.

Fixed tests so that travis passes

---

requirements.txt
vms/administrator/urls.py
vms/administrator/views.py

Migrated the report function in administrator app to CBV using two views inside one. GenerateReportView in administrator app used ShowFormView and ShowReportListView to display the form and generate the report respectively.

Migrated administrator application from FBV to CBV

---

requirements.txt

This PR is to add django-braces to the requirements file as its mixins are being used while migrating to Class Based Views

Added django-braces to requirements

---

vms/event/views.py

Corrected event editing request
Changed the form returned on post request if form.is_valid() is false. Instead of returning a  new form instance with post data changed it return the invalid form containing errors.
Fixes #345

Event editing request corrected

---

vms/event/views.py

Revert "Event editing request corrected"

---

vms/job/models.py
vms/job/templates/job/create.html
vms/job/templates/job/delete.html
vms/job/urls.py
vms/job/views.py

Migrated function based views in Job application to class based views. The following are the views used:
ListView - To list the jobs
UpdateView - To edit the Job details
DeleteView - To delete a job object
DetailView - Displays the details of a job

Migrated Job app to CBV

---

vms/organization/models.py
vms/organization/templates/organization/delete.html
vms/organization/urls.py
vms/organization/views.py

Migrated organization app from function based views to class based views. The following are the views used:
ListView - To list the orrganization
UpdateView - To edit the Oganizationdetails
DeleteView - To delete a Organization object

Migrated Organization app to CBV

---

aut_docs/Design_Document.md
aut_docs/Documented_failures.md
aut_docs/Setup.md

Also added list of all commented out tests cases for future reference

Updated AUT documentation

---

vms/authentication/templates/authentication/login.html
vms/authentication/urls.py
vms/authentication/views.py
vms/registration/urls.py
vms/registration/views.py
vms/vms/settings.py
vms/vms/templates/vms/base.html

Migrated authentication application from CBV using Django's auth views.
It used function based views for login and logout process earlier.
Registration application is migrated to TemplateView based calls view which
allows administrator and volunteer signup.
Also implemented generating a message when username and password mismatches
and phone number error.
Updated requirements to avoid tests failure, and corrected URLs

Migrated authentication and registration application from FBV to CBV

---

vms/volunteer/models.py
vms/volunteer/urls.py
vms/volunteer/views.py

Migrated the function based views in Volunteer app to class based views. The following are the the CBVs used  for migration:
UpdateView- To update volunteer profile
FormView- To display the volunteer form
ListView- To display the list of volunteers signed in
DetailView- To display the complete details of a volunteer

Migrated Volunteer app to CBV

---

vms/job/views.py

Removed the lines of code linked in [https://github.com/systers/vms/issues/389](#389) and removed extra spacing between functions in each class.
I left no spaces, not sure if that is a good thing. Let me know!

removed outdated code for function based views in views.py

---

vms/registration/views.py

I have added full stop at the end of various statements in comment section of views.py
Closes #381.

Addition of full stop at the end of various statements 

---

vms/registration/templates/registration/signup_volunteer.html
vms/registration/tests/test_functional_volunteer.py

Fixes the Volunteer Signup form.

---

docs/Installation Guide.md

Changes were not added to the guide to use the requirements file

Updated Installation guide to use requirements file

---

vms/authentication/views.py

Redirect index to login.

---

vms/event/forms.py
vms/event/services.py
vms/event/views.py

Fix the event search function

---

vms/shift/views.py

Disallows max volunteer field to be edited with invalid number.

---

vms/administrator/models.py
vms/event/models.py
vms/registration/tests/test_functional_admin.py
vms/shift/models.py
vms/volunteer/models.py

Generalize the model lengths.

---

vms/event/forms.py
vms/event/models.py
vms/event/tests/test_services.py
vms/job/tests/test_services.py

Make event names unique.

---

docs/Help!.md

Space needed b/ween # and 'header'

Format helpfiles markdown correctly

---

vms/vms/static/vms/jquery-custom/activate-datepicker.js

..and a bit of JS formatting on the file too.

[Fix #450] Imply 'yy-mm-dd' format for administrator report datepicker

---

.gitignore
vms/setup.cfg

Config pep8 behaviour at vms/setup.cfg and add line to .gitignore for ignoring .idea content

Added a configuration file for pep8

---

.gitignore
vms/.coveragerc

Exclude from coverage non .py files

Change .coveragerc to exclude from coverage non .py files

---

vms/administrator/urls.py
vms/administrator/views.py

related to #382, fix done for /admin/report.
now it is showing event_list.

Show event list dropdown box at adminstrator report section #382

---

vms/administrator/admin.py
vms/administrator/forms.py
vms/administrator/models.py
vms/administrator/tests/test_formFields.py
vms/administrator/tests/test_report.py
vms/administrator/tests/test_services.py
vms/administrator/tests/test_settings.py
vms/administrator/tests/test_unit.py
vms/administrator/urls.py
vms/administrator/utils.py
vms/administrator/views.py

adminAlphabeticalImports

---

vms/administrator/admin.py
vms/administrator/forms.py
vms/administrator/models.py
vms/administrator/urls.py
vms/administrator/utils.py
vms/administrator/views.py

Referencing issue #318 Run pycodestyle on vms

---

README.md

command for downloading and importing data for django-cities-light is added in README.md file.
Fixes #490. -Tapasweni

Added command to download and import data for django-cities-light.

---

vms/volunteer/templates/volunteer/report.html

Referencing #283 Display Message above page in case of no result in Admin Report

---

docs/Contribution_Guide.md
docs/Database_Schema.md
docs/Getting_Help.md
docs/Installation_Guide.md
docs/Project_Settings.md
docs/Software_Design.md

 Renamed files in vms/docs by replacing space by underscore

---

vms/administrator/templates/administrator/403.html
vms/administrator/templates/administrator/404.html
vms/administrator/templates/administrator/500.html

Closes #465 
I have created custom error pages and added the corresonding code to Administratoe/views.py and vms/url.py.

Created custom error pages for 403, 404,500

---

vms/volunteer/models.py

Now even profiles having numbers can be entered in the profile field.
Fixes #474.

Fixes #474

---

vms/administrator/tests/test_report.py
vms/administrator/tests/test_settings.py
vms/administrator/urls.py
vms/administrator/views.py

Referencing issue #379: Remove all 'import *' from code

---

.travis.yml
README.md
docker-compose.yml
docs/Installation_Guide.md
vms/vms/settings.py

Fixes : [#460](https://github.com/systers/vms/issues/460)
If i made a mistake please let me know!

Hide secret_key in settings.py

---

vms/volunteer/templates/volunteer/403.html
vms/volunteer/templates/volunteer/404.html
vms/volunteer/templates/volunteer/500.html

Referencing issue #465 Create custom error pages for 403, 404,500 

---

.travis.yml
requirements.txt

I have added Flake8 to .travis.yml, the test fails as flake8 command exits with status '1' due to it's warnings.

Added Flake8 to .travis.yml

---

vms/volunteer/views.py

Fixes #382 
Added dropdown for event suggestions in volunteer/report.

Added dropdowm for event suggestions in volunteer/report

---

vms/administrator/views.py
vms/volunteer/templates/volunteer/search.html
vms/volunteer/views.py

- Fix dropdown in admin/reports where job name and organization name are not listed.
- Allow admin  to search a user with organization name selecting from dropdown.
Fixes #520

Allow admin to select organization from dropdown and fix dropdown

---

requirements.txt
vms/vms/templates/vms/base.html

Hey @tapasweni-pathak 
The link to "About" page has been removed  referring to the issue https://github.com/systers/vms/issues/403.
Please review.

Implement about page

---

vms/administrator/tests/test_formFields.py
vms/administrator/tests/test_report.py
vms/administrator/tests/test_settings.py
vms/authentication/tests/test_login.py
vms/event/tests/test_shiftSignUp.py
vms/home/tests/test_functional.py
vms/job/tests/test_jobDetails.py
vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py
vms/shift/tests/test_manageVolunteerShift.py
vms/shift/tests/test_shiftDetails.py
vms/shift/tests/test_shiftHours.py
vms/shift/tests/test_viewVolunteerShift.py
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_volunteerProfile.py
vms/volunteer/tests/test_volunteerReport.py

ref https://github.com/SeleniumHQ/selenium/issues/3884.

Comment Firefox failing test case

---

vms/job/templates/job/create.html
vms/job/views.py

Referencing Issue #458: Keep the event to last changed value

---

README.md

Accidentally added a Travis shield even though one already existed. Reverts systers/vms#553

Revert "Added Travis shield"

---

vms/vms/settings.py

Media root added in settings.py to fix the error uploading resume 
Fixes # 555, #305 
- Code

Error in uploading resume fixed

---

vms/volunteer/templates/volunteer/profile.html

Unselected organisation aligned to center in profile of volunteer.
Fixes #583
- Code

non listed organisation aligned to center

---

vms/volunteer/views.py

Spelling errors fixed in commented code.
Fixes #588

spelling errors fixed in commented code

---

vms/administrator/templates/administrator/edit.html
vms/administrator/templates/administrator/profile.html
vms/administrator/urls.py
vms/administrator/utils.py
vms/administrator/views.py
vms/vms/templates/vms/base.html

Added a service to get admin object by id. Added profile view and edit templates and views. Updated base.html and urls.py accordingly
Fixes #554 
- Code

Added pages to view and edit admin profile.

---

vms/volunteer/models.py

I have added str function in Volunteer model

adding str into model

---

vms/volunteer/views.py

get_volunteer_by_id and has_resume_file is imported in views from services.
Fixes #561 
- Code

get_volunteer_by_id not found error solved while editing profile

---

vms/volunteer/views.py

initialize the `organizations_list` outside the if statement.
Fixes #633 
- Code

Fix scope of organizations_list

---

README.md

Changed the broken link of Installation Guide in README.md
Fixes #641
Updated link - https://github.com/systers/vms/blob/develop/docs/Installation_Guide.md

Fixed broken link of Installation Guide in README.md 

---

vms/job/views.py

This pull request contains a patch for a bug which allows a user to create multiple jobs for a single event with same titles. 
Fixes #330 
- Code
This issue has been fixed now and here's the screenshot of issue.
After applying the patch here's the screenshot.

Fix multi job creation with same name

---

vms/shift/views.py
vms/vms/utils.py

Removed unreachable render statements from utils.py to cleanup the code
Fixes #627 
- Code
Code quality related change, hence no testing required.
@tapasweni-pathak @MeepyMay @tonythomas01 Please review this

Removed unreachable lines of code in vms/utils

---

README.md

As a contributor,
I need to set up my environment for the project using docker,
so that I can contribute to project.
I faced issue :Unable to find image 'vms:latest' locally
Change docs for vms 6th step
from Run docker run -e SECRET_KEY=foobarbaz vms
to
Run docker run -e SECRET_KEY=foobarbaz vms_web

Update Docker Setup Wiki #667

---

vms/registration/templates/registration/signup_volunteer.html

Stopped display of resume if it is 'None'
Fixes #602 
- Code

Replace 'None' by placeholder in  resume upload field of volunteer sign up form

---

vms/administrator/templates/administrator/edit.html
vms/job/templates/job/create.html
vms/job/templates/job/edit.html
vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html
vms/vms/static/vms/js/hide-organization.js
vms/vms/static/vms/js/hide_organization.js
vms/vms/static/vms/js/timepicker.js
vms/vms/static/vms/js/update-event-dates.js
vms/volunteer/templates/volunteer/edit.html

The javascript functions are updated according to Javascript Standards.
Fixes # https://github.com/systers/vms/issues/677
- Code
- Outreach

update javscript according to standards

---

vms/authentication/urls.py

Class based views have been implemented for Login and Logout replacing function based views.
Fixes #708
- Code

login and logout class based view added

---

vms/administrator/tests/test_formFields.py
vms/administrator/tests/test_report.py
vms/administrator/tests/test_settings.py
vms/organization/models.py
vms/organization/tests/test_model.py
vms/organization/tests/test_organization.py
vms/pom/locators/eventsPageLocators.py
vms/pom/pages/authenticationPage.py
vms/pom/pages/basePage.py
vms/pom/pages/eventsPage.py
vms/pom/pages/homePage.py

Tested Organization app
- Move tests from automated testing repo
- Write my own tests
Closes #718 
- Code
```
python manage.py test organization -v 2
```
```
```

Testing Organization app

---

vms/shift/views.py

Adds form_class to ViewHours view to solve the NoneType error.
Fixes #727 
- Code

form class added for form view

---

vms/administrator/templates/administrator/profile.html
vms/administrator/templates/administrator/report.html
vms/shift/templates/shift/sign_up.html
vms/vms/static/vms/css/style.css
vms/volunteer/templates/volunteer/profile.html
vms/volunteer/templates/volunteer/report.html

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #746 
- Code

Replace nbsp by padding and alignment

---

vms/pom/pages/adminRegistrationPage.py
vms/pom/pages/volunteerRegistrationPage.py
vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py
vms/registration/tests/test_services.py
vms/registration/tests/test_unit.py
vms/registration/views.py

Tested Registration app
Closes #721 
- Code
```
python manage.py test registration -v 2
```
```
```

Testing Registration app

---

.travis.yml
setup-geckodriver.sh

Created a bash script to configure geckodriver setup.
Fixes #764 
- Code

Bash script for configuring geckodriver

---

vms/shift/utils.py

Modified first_name and last_name field of admin and volunteer which were being created.
Fixes #762 
- Code
Checked that the existing tests are not failing since extra fields if were wrong should've raised errors.

Add first_name and last_name for admin and volunteer

---

vms/registration/views.py

This PR removes the debug print statements making the logs pretty.
Fixes #793 
- Code
See travis log, registration tests no longer print DOM's.

Remove debug print statements

---

.travis.yml
requirements.txt
setup-geckodriver.sh
vms/authentication/forms.py
vms/authentication/tests/test_login.py
vms/authentication/tests/test_services.py
vms/pom/locators/volunteerProfilePageLocators.py
vms/pom/pages/authenticationPage.py
vms/pom/pages/basePage.py
vms/pom/pages/volunteerProfilePage.py
vms/pom/pages/volunteerReportPage.py
vms/pom/pages/volunteerSearchPage.py
vms/registration/views.py
vms/shift/utils.py
vms/volunteer/models.py
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_services.py
vms/volunteer/tests/test_unit.py
vms/volunteer/tests/test_volunteerProfile.py
vms/volunteer/tests/test_volunteerReport.py
vms/volunteer/views.py

Gsoc18 infra commits
- Code
- Outreach

Gsoc18 infra commits

---

vms/shift/templates/shift/volunteer_shifts.html

The volunteers can not log the upcoming shifts.
Fixes #740  
- Code

Log hours constraint added

---

vms/pom/locators/adminRegistrationPageLocators.py
vms/pom/locators/volunteerRegistrationPageLocators.py
vms/pom/pages/adminRegistrationPage.py
vms/pom/pages/volunteerRegistrationPage.py
vms/registration/forms.py
vms/registration/passwordmatch.py
vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html
vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py
vms/registration/utils.py
vms/registration/views.py

The user needs to confirm password for his account while sign up .
Fixes #616 
- Code

Password confirmation added in signup form for volunteer and administrator

---

vms/pom/locators/upcomingShiftsPageLocators.py
vms/registration/tests/test_functional_volunteer.py
vms/shift/tests/test_viewVolunteerShift.py

Fix failing tests

---

vms/shift/admin.py
vms/shift/forms.py
vms/shift/models.py
vms/shift/services.py
vms/shift/templates/shift/hours_list.html
vms/shift/templates/shift/request_admin.html
vms/shift/tests/test_manageVolunteerShift.py
vms/shift/tests/test_shiftHours.py
vms/shift/tests/test_unit.py
vms/shift/urls.py
vms/shift/utils.py
vms/shift/views.py

The volunteer can request editing of log hours from admins within a week.
Fixes #804 
- Code

Editing request option enabled for editing log hours

---

vms/pom/tests/tests.md

Since POM needs tests which have already been implemented, so rather than writing them this PR documents them in a markdown file.
Fixes #755 
Simple markdown file, can be viewed directly in the PR.

Document POM tests

---

vms/authentication/forms.py
vms/authentication/templates/authentication/login.html
vms/authentication/templates/registration/password_reset_complete.html
vms/authentication/templates/registration/password_reset_confirm.html
vms/authentication/templates/registration/password_reset_done.html
vms/authentication/templates/registration/password_reset_email.html
vms/authentication/templates/registration/password_reset_form.html
vms/authentication/templates/registration/password_reset_subject.txt
vms/authentication/tests/test_login.py
vms/authentication/urls.py
vms/authentication/views.py
vms/pom/locators/authenticationPageLocators.py
vms/pom/pageUrls.py
vms/pom/pages/authenticationPage.py
vms/vms/settings.py

Django authentication inbuilt views have been used to implement the feature.
Fixes  #683 
Code

password forgot feature implemented

---

vms/event/templates/event/details.html
vms/event/templates/event/list.html
vms/event/tests/test_event.py
vms/event/tests/test_searchEvent.py
vms/event/urls.py
vms/event/views.py
vms/pom/locators/eventsPageLocators.py
vms/pom/pages/eventsPage.py

Detail view is added for events which shows description, city, state, country, start date, end date of the event.
Fixes #751 
- Code

detail view added for events

---

vms/pom/locators/volunteerSearchPageLocators.py
vms/pom/pages/volunteerSearchPage.py
vms/volunteer/forms.py
vms/volunteer/services.py
vms/volunteer/templates/volunteer/search.html
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_services.py
vms/volunteer/views.py

Add event and job in search volunteer form
Fixes #773 
- Code

Event and job fields add in Volunteer search form

---

requirements.txt
vms/event/tests/test_api.py
vms/event/urls.py
vms/event/views.py
vms/vms/settings.py

API to communicate with Vola
Fixes #820 
- Code

Vola api implementation

---

vms/administrator/tests/test_settings.py
vms/event/tests/test_shiftSignUp.py
vms/job/forms.py
vms/job/services.py
vms/job/templates/job/list.html
vms/job/templates/job/list_sign_up.html
vms/job/tests/test_searchJob.py
vms/job/tests/test_services.py
vms/job/urls.py
vms/job/views.py
vms/pom/locators/eventSignUpPageLocators.py
vms/pom/locators/jobSearchPageLocators.py
vms/pom/pages/eventSignUpPage.py
vms/pom/pages/jobDetailsPage.py
vms/pom/pages/jobSearchPage.py
vms/shift/templates/shift/list_jobs.html

Job Search Form with fields namely name, start date, end date, city, state, country, job is created.
Fixes #768 
- Code

Job search admin

---

vms/administrator/tests/test_unit.py
vms/shift/utils.py

This PR adds model tests for administrator app along with checking all the fields of admin model.
Fixes #780 
- Code
```
python manage.py test administrator.tests.test_unit -v 2
```

Add model tests for administrator

---

vms/administrator/tests/test_settings.py
vms/shift/forms.py

Added logic for checking start and end time in shift app.
Fixes #741 
- Code

Add logic for checking time in shift form

---

requirements.txt
vms/administrator/templates/administrator/confirm_report.html
vms/administrator/templates/administrator/pdf.html
vms/administrator/templates/administrator/reject_report.html
vms/administrator/tests/test_report.py
vms/administrator/views.py
vms/vms/settings.py

Send email to volunteer on report confirmation along with report pdf.
Fixes #805 
- Code
- Outreach

Report pdf

---

vms/authentication/templates/registration/password_change_done.html
vms/authentication/templates/registration/password_change_form.html
vms/authentication/tests/test_login.py
vms/authentication/urls.py
vms/home/tests/test_functional.py
vms/pom/locators/authenticationPageLocators.py
vms/pom/locators/homePageLocators.py
vms/pom/pageUrls.py
vms/pom/pages/authenticationPage.py
vms/pom/pages/homePage.py
vms/vms/templates/vms/base.html

The user can now change his password 
Fixes #522 
- Code

Password change feature add

---

vms/administrator/tests/test_settings.py
vms/event/templates/event/create.html
vms/event/urls.py
vms/event/views.py
vms/pom/pages/eventsPage.py
vms/vms/urls.py

Create events from meet up data supplied by Portal
Fixes #796 
- Code
- Outreach

Communicate with Portal api to create events

---

vms/pom/pages/adminRegistrationPage.py
vms/registration/templates/registration/acc_active_email.html
vms/registration/tests/test_functional_admin.py
vms/registration/urls.py
vms/registration/views.py

Email confirmation for admins
Fixes #844 
- Code
- Outreach

email confirmation added

---

vms/administrator/templates/administrator/profile.html
vms/pom/locators/volunteerReportPageLocators.py
vms/pom/pages/volunteerReportPage.py
vms/shift/templates/shift/sign_up.html
vms/vms/static/vms/css/style.css
vms/volunteer/templates/volunteer/profile.html
vms/volunteer/templates/volunteer/report.html
vms/volunteer/templates/volunteer/view_history.html
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_volunteerReport.py

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
- Code
- Outreach

Nbsp removal

---

vms/shift/templates/shift/request_status.html

Template added for edit request email
Fixes #849
- Code
- Outreach

template addded

---

vms/registration/views.py

The dropdown of organization list gets populated without restart  of server
Fixes #652 
- Code
- Outreach

Organization name update in form 

---

vms/registration/templates/registration/signup_volunteer.html
vms/vms/static/vms/js/hide_resume_textbox.js
vms/vms/templates/vms/base.html

The textbox for resume link hides if volunteer uploads a resume file.
Fixes #624 
- Code

Hide textbox for resume link if resume file is uploaded in sign up form

---

vms/event/views.py
vms/vms/templates/vms/no_connection.html

Exception page for portal api in case of no connection added
Fixes # 865
- Code
- Outreach

Exception page for portal api in case of no connection

---

docs/Database_Schema.md

database doc updtaed according to gsoc18 feature updates.
Fixes #862 

Database doc updated

---

vms/registration/views.py

Now the volunteers and admins can sign up without any existing organization in database.
Fixes #576 
- Code
- Outreach

Registration allowed with empty organization database

---

docs/GSoC18.md

Gsoc18 documentation
- Code
- Outreach

Gsoc18 documentation

---

requirements.txt

`psycopg2` upgraded from `2.7.3` to `2.7.4` that resolve the errors users get while following the  procedure to set up the project locally. These Changes are made in requirements.txt.
Fixes #895 
NA

Changes psycopg2 to version 2.7.4

---

vms/pom/pages/basePage.py
vms/pom/pages/eventSearchPage.py
vms/pom/pages/jobSearchPage.py
vms/pom/pages/volunteerSearchPage.py

Move get_results_list method

---

vms/event/models.py
vms/shift/models.py

The file models.py is changed in two of the apps as an error occurred if comma is included in the address field.
Fixes #897 
- Code
Changed the code and tested on my local machine.

Fix error in address field due to inclusion of comma.

---

aut_docs/Installation_Setup.md

This concise installation guide removes the unnecessary information from [this guide](https://github.com/anitab-org/vms/blob/develop/docs/Installation_Guide.md) and fills the gaps and left out instructions regarding Postgres DB setup in [this guide](https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md). Other missing steps and/or notes for potential errors have been edited/added. The link in readme doesn't need to be updated, the changes have been made in that file only.
fixes #932 
This guide has been tested on a virtual box. It guides the user without error.

A concise Installation Guide

---

vms/vms/settings.py

fixes #920
Removes redundant code in settings.py
fixes #920
- Code
N/A

Removed redundant code

---

vms/administrator/templates/administrator/profile.html
vms/volunteer/templates/volunteer/profile.html

Fixed Issue #886
Fixes # [886]
- Code
Open profile page, the username should not be clipped anymore.

Issue #886 fixed

---

vms/registration/templates/registration/signup_volunteer.html

Fixed the volunteer sign up page. It has a small bug of an endif template tag. I have added that to it.
Fixes #950
- Code
- Bugfix (non-breaking change which fixes an issue)
The signup page is not opening up. I have fixed the issue and tested it by opening up the given Url.

Fixed the volunteer sign up page 

---

vms/vms/static/vms/css/style.css
vms/vms/templates/vms/base.html

The navbar was overlapping with the logo and the responsive view of the navbar was unaligned.
Fixes #900
Firefox and Chrome with the Dev Tools

Fix: Overlapping menu on sign up

---

.gitignore
vms/vms/urls.py

This pull request adds staticfiles and media root to urlpatterns in urls.py file of vms module. 
Fixes #951
- Code
The code has been run on my local computer.
**Screenshots**
Browser output after signing up - no errors
Terminal Logs of running server - no errors and email also confirmed

Code: Add staticfiles to urlpatterns in vms/urls.py

---

README.md

Completed missing parts and updated outdated sections in Readme.md.
Fixes #969 

docs: Complete missing parts and update outdated sections in Readme.md

---

README.md

Added a badge to join zulip chat for VMS project
Fixes #990 

docs: added a badge to join zulip chat

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUESTS.md

added FEATURE_REQUESTS.md and BUG_REPORT.md  as a part of the open-source hack
Fixes #1026 
Delete irrelevant options.
Added and previewed markdown files.
Delete irrelevant options.

Added separate templates for feature request and bug report

---

vms/home/templates/home/home.html

To add button in UI to link Zulip
Fixes #1038  
Successfully added button in UI to link Zulip. When a registered user is logged in the button is shown on the home page.
Screenshot:

Added Button in UI to link Zulip

---

README.md

- Add a codecov badge (#1062) 
- Updated the readme file title from `AnitaB.org Portal - VMS project` to `Volunteer Management System(VMS)`
Fixes #1062
`Before Changes were made:`
`After Changes were made:`

docs: add a codecov badge (#1062)

---

README.md

- Add a codecov badge (#1062) 
- Updated the project title in readme file from `AnitaB.org Portal - VMS project` to `Volunteer Management System(VMS)`
Fixes #1062
`Before changes were made:`
`After changes were made:`

docs: add codecov badge & update title

---

docs/outreach-work.md

Blog on my OSH Experience.
Fixes #1142
- Outreach
The Medium link is provided in the outreach-work.md file in docs.

docs: Blog on My OSH Experience

---

vms/registration/views.py

Fix admin registration issue while signing up.
Fixes #1002
- Code
successfully able to register.

fix: Admin registration issue
