vms/organization/services.py
vms/organization/tests.py

Unit test for delete_organization and if statement

---

docs/Installation Guide.md

Addresses issue #32. 
An example of the installation of the psycopg2 package has been added. 
Minor text edits as well.

Add detail on psycopg2 installation #32

---

vms/event/services.py
vms/event/tests.py

There are new unit tests for all functions in event: event_not_empty, delete_event, get_event_by_id, get_events_ordered_by_name.
I also created a new function event_not_empty in event/services.py based on the https://github.com/systers/vms/issues/34 and https://github.com/systers/vms/pull/28#issuecomment-109354934.

New unit tests for event

---

vms/.coveragerc

The `.coveragerc` file is added for the convenience of developers running coverage locally during development. Relates to #11

Add coverage config file for local development testing

---

vms/shift/services.py
vms/shift/tests.py

Issue https://github.com/systers/vms/issues/65
Add functionality so that a shift cannot be deleted if at least one volunteer is signed up for it or has logged hours for it.
Functions have been supplemented:
- delete_shift in services.py
- test_delete_shift in tests.py

Functionality so that a shift cannot be deleted

---

vms/registration/views.py
vms/shift/services.py
vms/shift/tests.py
vms/volunteer/forms.py
vms/volunteer/models.py
vms/volunteer/templates/volunteer/edit.html
vms/volunteer/templates/volunteer/profile.html

Issue https://github.com/systers/vms/issues/70
The new function ```send_notification(days)``` sends one day or one week shift-notifications to all volunteers who signed up for the shift. This function should be run on the server **once a day**.
Example data:
```
v1 = Volunteer(
first_name="Valeria",
last_name="Bogdanova",
address="MyAddress",
city="MyCity",
state="MyState",
country="MyCountry",
phone_number="2374983247",
email="vubogdanova@gmail.com",
user=u1
)
v1.save()
e1 = Event(
name="GHC 2015",
start_date="2015-07-22",
end_date="2015-08-23"
)
e1.save()
j1 = Job(
name="Volunteer Coordinator",
start_date="2015-07-22",
end_date="2015-08-23",
description="Volunteer Coordinator",
event=e1
)
j1.save()
s1 = Shift(
date=date.today() + timedelta(1), #tomorrow date
start_time="12:00", …
```

Email notifications

---

vms/event/templates/event/create.html
vms/event/views.py
vms/volunteer/models.py

Issue https://github.com/systers/vms/issues/78

Not allowing to create a post dated event

---

.editorconfig

This PR adds a config file for EditorConfig.  The settings are based on the settings suggested by Danny Greenfeld, author of 2 scoops of django.
Closes #115

Add editorconfig settings

---

vms/event/services.py
vms/event/templates/event/edit.html
vms/event/tests.py
vms/job/templates/job/edit.html
vms/shift/models.py
vms/shift/templates/shift/create.html
vms/shift/views.py

Inspired by @willingc. Closes https://github.com/systers/vms/issues/100
This PR adds a pre-populate feature for creating shifts. 
The shift-fields are filled with database information already know about the event (country, state, city, address, venue) to minimize typing by admin. The admin is able to override the pre-populated information.

Enhance UI for creating shifts

---

vms/administrator/models.py
vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html
vms/vms/templates/vms/base.html
vms/volunteer/models.py

Closes https://github.com/systers/vms/issues/94.
Related also to https://github.com/systers/vms/issues/97.
Before typing you can see a prompt:
Error message is more helpful now:

Phone number registration and menu item name

---

vms/shift/services.py
vms/shift/views.py

Closes https://github.com/systers/vms/issues/112
After these changes, in the list /shift/list_shifts_sign_up/ a volunteer can see all shifts except those for which she/he has signed up. And she/he will not receive any error messages.

Show all shifts except signed up

---

vms/job/templates/job/create.html
vms/job/views.py
vms/shift/templates/shift/create.html
vms/shift/views.py

Changes were made in views.py and create.html to avoid creating job outside events and shifts outside jobs.
One example of error is as follows:
https://gyazo.com/f4a89f674095f73238e2ab242876f8dc

Dates Check 

---

vms/shift/templates/shift/edit.html
vms/shift/views.py

Extends #132 
job names and dates now show up in shift editing as well to match the creation.

Simplify editing of the shift

---

vms/event/services.py
vms/event/views.py
vms/job/services.py
vms/job/views.py

closes #175 
Volunteers will only be able to see events with jobs (at least 1 job must have a shift), and jobs with shifts.
What admin sees:
What volunteer sees:

Show only not empty events and jobs

---

vms/job/templates/job/create.html
vms/job/templates/job/edit.html
vms/vms/static/vms/js/update-event-dates.js

The event dates are now shown in both job creation and editing as separate fields, and will change based on what event is chosen.
job creation example:
job editing example:

Show event dates for job create and edit

---

docs/Contribution Guide.md

The new documentation added will help guide contributors on what to do if they want to help the VMS project.
Example of the first half of the documentation:

Add a how to "contribution guide" in documentation

---

docs/Getting Help.md

The getting help guide should help new contributors learn what to include and remember when asking questions.
Sample of the documentation:

Add getting help guide in documentation

---

docs/Installation Guide.md

As mentioned previously in installation guide, after following all the steps as required 
When we go to the link http://localhost:8000/home/ there is a connection error.
Actually the link is supposed to be http://localhost:8001/home/ for which we get the vms
So, the link needs to be updated.

Updated the link to run vms on local machine

---

vms/job/templates/job/edit.html
vms/job/views.py

Before:
When a job was created,it didn't allow start date and end date to be outside event dates.
But when the job was edited,it showed no error for dates outside that of event dates.
Now : 
It shows error message as in create job page for edit page if dates selected were not valid.
Please review and suggest changes.

Fixed edit job date validity

---

vms/shift/templates/shift/edit.html
vms/shift/views.py

Before:
When a shift was created,it didn't allow start date and end date to be outside job dates.
But when the shift was edited,it showed no error for dates outside that of job dates.
Now :
It shows error message as in create shift page for edit page if dates selected were not valid.
Fixed #193 
Please review and suggest changes.

Fixed edit shift date validity

---

vms/shift/templates/shift/add_hours.html
vms/shift/templates/shift/add_hours_manager.html
vms/shift/templates/shift/edit_hours.html
vms/shift/templates/shift/edit_hours_manager.html
vms/shift/views.py

Before:
If in log hours ,the end time was before the start time. No errors were raised and the hours were logged successfully.
Now: End time has to be greater than start time.
Fixed #195 
Please review and suggest changes.

Fixed log hours validity

---

vms/vms/settings.py

This fixes the error **password authentication failed for user "myuser"**. 
It was also pointed by a GCI participant, [here](http://gci-maydha.blogspot.in/2015/12/installing-volunteer-management-system.html).

Change the default username and password in settings file

---

vms/event/services.py
vms/event/templates/event/edit_error.html
vms/event/tests.py
vms/event/views.py
vms/job/services.py
vms/job/templates/job/edit_error.html
vms/job/tests.py
vms/job/views.py

This PR attempts to allow editing of event/job in two possible situations:
1. There are no associated jobs/shifts
2. If dates are changed for event/job and they don't result in discrepancies for associated jobs/shifts
In remaining cases, editing is not allowed and an appropriate error message is displayed as shown below:
Since I have added some functions in services.py, I have added tests for them.
I have broken down the commits in a previous PR ( #212) and made a new request. In addition, while editing jobs/views.py I came across some other errors which occur in the jobs view ( Please see #229 ). I have tried to resolve these. 
So now additionally,
1. While editing jobs, job dates are checked to see if they lie in the valid range.
2. While editing shifts, shift dates are checked to see …

Fixed editing issues for events and jobs

---

vms/shift/views.py

Fixes #228 and #236 
The previous code after a recent merge seemed to have some indentation issues and duplicated code :worried: .due to which the above error were faced
After these changes:
1. It is checked that the shift dates lie between the job dates while editing
2. The concerns in #195 for logging hours are addressed
3. Merged with latest change to check time for edit shifts
4. Added time check for create shifts
Please do crosscheck and suggest changes

Fixes validity errors while editing shifts and indentation errors in the file

---

vms/registration/phone_validate.py
vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html
vms/registration/views.py
vms/vms/settings.py
vms/volunteer/models.py

Earlier, there was no validation for phone numbers with respect to the country. This PR attempts to do that with the help of [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) package. I tested this change successfully for a few phone numbers (mostly India based) and verified it with [javascript](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) / [java](http://libphonenumber.appspot.com/) demo. Country codes available at [geonames](http://www.geonames.org/countries/)
There are two dependencies required - django-cities-light and phonenumbers.
For cities-light installation - [here](https://github.com/yourlabs/django-cities-light)
`pip install django-cities-light`
Adding to settings (already done)
`python manage.py …

Validation of phone numbers based on country

---

vms/home/templates/home/home.html
vms/registration/views.py

The current approach shows a 503, which is replaced with a friendly
bootstrap alert message in this commit.
Fixes  #257

Show better error mesasge when no organization exists on Sign Up

---

vms/registration/templates/registration/signup_administrator.html
vms/registration/templates/registration/signup_volunteer.html
vms/vms/static/vms/js/hide_organization.js

If the admin/volunteer selects a organization from the dropdown menu, the text input for 'others' will disappear. If none of the organization is selected then it will appear again. 
Closes #106

Hide textbox if organization selected

---

vms/event/services.py
vms/event/tests.py
vms/job/services.py
vms/job/tests.py
vms/volunteer/templates/volunteer/report.html
vms/volunteer/views.py

Creates a dropdown for events and jobs in volunteer report - Rather than displaying an entire list of events and jobs, only the ones that volunteer has signed up for are displayed since there wouldn't be any results returned for other events/jobs. This keeps the length of the lists small, only listing those which are relevant for a particular volunteer. This can also be modified from including signed up events/jobs to including only logged events/jobs. 
Fixes #290
New services and their tests have also been added. Please review and suggest changes

Dropdown for volunteer report

---

vms/administrator/templates/administrator/report.html
vms/administrator/views.py

Minor change to prevent event value from getting reset on page reload in admin report
Fixes #292 , Please review and suggest changes

Saving selected event dropdown option in report on reload

---

vms/event/views.py

Pertaining to the issue [#301](https://github.com/systers/vms/issues/301), this PR fixes the problem by retaining the end date of event along with the other information (except the faulty start date field).

Retains end date in event edit; on wrong start date

---

vms/event/views.py

As per issue [#307](https://github.com/systers/vms/issues/307) , the `end-date` field would go blank after saving the form with blank `start-date` field (which goes blank on an erroneous entry). This PR resolves the issue by retaining all the entries of the field including the `end-date` field.
Closes  [#307](https://github.com/systers/vms/issues/307)

Retains end date in event edit on erroneus entry

---

vms/home/urls.py

The function based view in home application was migrated to TemplateView and the file views.py in home application was deleted as it was empty. 'from home import views' statement in home/urls.py resulted in an error as the file views.py was removed. The error is corrected by removing the statement.

Removed 'from home import views' statement in home/urls.py

---

vms/event/tests/test_shiftSignUp.py
vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py

This PR is to add automated tests for admin/volunteer registration and shift sign up page
Earlier, 3 tests existed for name, address and city fields on admin/volunteer registration page.
Now tests for state, country phone number, organization and email have been added. The tests for address, city, state, country have been clubbed as a single location test, hence ensuring that 1 test does the job which earlier 4 tests would have completed. This has been done for both volunteer and admin separately.
Please review.
@tapasweni-pathak I have added in more tests here for the shift sign up page too. The list of all tests now added are
- test for phone field (both volunteer and admin)
- test for state field (both volunteer and admin)
- test for email field (both volunteer and admin)
- test for …

Add automated tests for registration and shift sign up page

---

.travis.yml
requirements.txt

This PR sets up continuous integration with travis for systers vms repository. For convenience, a separate requirements.txt file has been updated with all the installations easier. The database credentials (vmsadmin and password ) have been removed to allow travis to login as default postgres user and carry out the tests. The travis file has also been configured to support GUI and headless browser testing.
After merging this PR, every commit/PR to the VMS repository will be checked to see if they break the tests (unit as well as functional). The requirements.txt file will also make vms setup more convenient.
_The build is failing at this point._ This failure is due to failing automated tests due to bugs (#327 and #325 ). Link to latest travis build - …

Adding continuous integration with travis

---

vms/administrator/tests/test_settings.py

This PR is to add the following tests for administrator roles that haven't been covered yet
- 6 tests for entering null values in create/edit event, create/edit shift and create/edit job form
- Test for deletion of a shift which has registered volunteers
- 2 tests to verify that end hours should be greater than start hours in create/edit shift form
- 2 tests to verify that the shift date should lie between the job dates in create/edit shift form
- 2 tests to verify that the job dates lie between the event dates in the create/edit job form
- Test for editing date of an job such that its shifts no longer fall within the job date range
- Test for editing date of an event such that its jobs no longer fall within the event date range
- Test for creating/editing an event with a start date later …

Added new selenium tests for administrator role

---

vms/.coveragerc

This PR modifies the configuration file for coverage. It omits a few files from coverage measurement, namely all tests and parts of the codebase which do not need to be tested.
The coverage is decreasing here as the amount of code to be used for coverage measurement is decreased

Updated coverage configuration

---

vms/administrator/tests/test_formFields.py
vms/administrator/tests/test_settings.py
vms/job/tests/test_jobDetails.py
vms/shift/tests/test_shiftDetails.py
vms/shift/tests/test_shiftHours.py

This PR is to add remaining tests from last week as well as the tests for this week. I am putting a separate PR so that it is easier to review. The tests include -
- test for job details
- 3 tests for shift details view (due to 3 test situations : when no volunteers are registered for a shift, when volunteers are registered but haven't logged hours and when hours are logged)
- 3 tests for checking that values in event, shift and job form are not lost when the page reloads
- test for checking if a shift can have 0 volunteers (validating max volunteer field)
- test to check that logged hours fall between the shift hours
- test for simplify shift
In addition to this, there are 3 more tests which have been commented out:
- 2 tests for checking that event is unique and job within event is …

Added Selenium tests

---

vms/administrator/tests/test_formFields.py
vms/administrator/tests/test_report.py
vms/administrator/tests/test_settings.py
vms/authentication/tests/test_login.py
vms/event/tests/test_shiftSignUp.py
vms/home/tests/test_functional.py
vms/job/tests/test_jobDetails.py
vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py
vms/shift/tests/test_manageVolunteerShift.py
vms/shift/tests/test_shiftDetails.py
vms/shift/tests/test_shiftHours.py
vms/shift/tests/test_viewVolunteerShift.py
vms/shift/utils.py
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_volunteerProfile.py
vms/volunteer/tests/test_volunteerReport.py

All selenium tests have been restructured to share code in this PR. Functions which could be possibly reused have been identified and created for the tests. In most tests, constants have also been isolated at the top so that any change in UI only requires a change at the beginning of the file.
There is reduction in both test times and lines  as follows -
Time (approx. ) - 75 min to 43 min (41-42% reduction)
Lines - 
Number of tests have also increased from 164 to 168 but these are not new tests. I have broken subparts of a few tests into separate ones as they were repeatedly testing the same thing
Travis build timings - 
Related to #369

Restructuring selenium tests

---

vms/event/forms.py
vms/event/models.py
vms/event/templates/event/delete.html
vms/event/templates/event/edit.html
vms/event/urls.py
vms/event/views.py

Migrated function based views in Events app to class based views. The following are the views used:
ListView - To list the Events
UpdateView - To edit the Event details
DeleteView - To delete a Event object

Migrated Events app to CBV

---

README.md

@tapasweni-pathak Students are getting confused as the old link uses a guide which isn't updated. All the documentation updates are being made in the docs/installation guide. Can you please merge this soon?

Updated link of guide in readme

---

vms/administrator/utils.py
vms/administrator/views.py
vms/event/views.py
vms/registration/utils.py
vms/registration/views.py
vms/volunteer/views.py

Stop volunteers from accessing admin urls.

---

vms/event/views.py
vms/shift/tests/test_viewVolunteerShift.py
vms/shift/views.py
vms/vms/templates/vms/no_volunteer_access.html
vms/volunteer/utils.py
vms/volunteer/views.py

Stop volunteers from accessing each other's urls.

---

vms/event/templates/event/edit.html
vms/event/views.py

Closes #397 
GH link : https://github.com/systers/vms/issues/397
- event/views.py : EventUpdateView.get_context_data() added
to set job start and end dates to context.
- event/templates/event/edit.html : Modified to display job dates.

Event editing now shows job dates

---

vms/shift/templates/shift/add_hours.html
vms/shift/templates/shift/add_hours_manager.html
vms/shift/templates/shift/edit_hours.html
vms/shift/templates/shift/edit_hours_manager.html
vms/shift/views.py

Closes #409 
GH link : https://github.com/systers/vms/issues/409
- views.py : AddHoursView and EditHoursView modified to pass
shift and volunteer shift values to render.
- templates/shift/add_hours.html : Modify to display shift hours.
- templates/shift/edit_hours.html : Modify to display shift and logged
shift hours.

Logging hours (adding & editing) shows shift time

---

vms/vms/static/vms/css/style.css

Closes https://github.com/systers/vms/issues/569

vms_style.css: Remove extra space from report template

---

vms/volunteer/views.py

When a user tries to check the report, nothing appears in job list dropdown.Added the job lists by including job list in context.
Fixes #572 
- Code
Tested on a local development system. Refer screenshots.
Added a job.

Added jobs in the job list while viewing the report form as volunteers

---

vms/vms/templates/vms/base.html

Earlier when the user logged in as a Django admin [superuser], he/she was not able to log out as there was no button present. Added the log out button.
Fixes #579 
- Code
Tested on local development. Refer screenshots.

Added a logout button for the django-admin.

---

vms/volunteer/views.py

In the volunteer search form of an admin account, list of organizations appeared to be empty after pressing search button once. Now its fixed.
Fixes #594 
- Code

Fixes issue #594

---

vms/volunteer/views.py

Organisations are now displayed in the volunteer profile edit form.
Fixes #580 #581 
- Code
Tested on a local development system. Refer the screenshots.
**Organisations** appear in the list.

Displaying Organisation List in the volunteer profile edit form.

---

vms/volunteer/templates/volunteer/edit.html

If the user has selected from the listed organisations , then the unlisted organisation textbox doesn't appear.
Fixes #622 
- Code

Hide textbox for unlisted organisation in edit profile form if an organisation is selected from given list

---

vms/volunteer/templates/volunteer/profile.html

The elements of a table are aligned to left and nbsp has been removed, replacing it with padding.
Fixes #618 
- Code

Fix indentation and implement table cell padding in volunteer's profile.

---

vms/administrator/models.py
vms/volunteer/models.py

The signup form for both administrators and volunteers were not accepting some special characters( like . or , or : ) which are often required in addresses. I have fixed the regex formats to correct this.
Fixes #645 
- Code
I ran the changes on local server : Here are the mocks -

Fixed address field regex parameters to allow some special charecters

---

vms/vms/static/vms/jquery-custom/activate-datepicker.js

The administrator can only select the upcoming or today's date as start and end dates while creating an event.
Fixes #651 
- Code

Restrict start date and end dates of event to upcoming ones

---

tests/administrator/test_working.py
tests/authentication/test_working.py
tests/event/test_working.py
tests/home/test_working.py
tests/job/test_working.py
tests/organization/test_working.py
tests/pom/test_working.py
tests/registration/test_working.py
tests/shift/test_working.py
tests/volunteer/test_working.py

This PR aims to create a base module for Tests in root of project where all the tests will be written.
Fixes #674 
- Code
Run the following command in root of project
```
python vms/manage.py test Tests/
```

Create Base module for Tests

---

vms/event/models.py
vms/event/tests/test_event.py
vms/event/tests/test_model.py
vms/event/tests/test_services.py
vms/event/tests/test_shiftSignUp.py
vms/event/tests/test_unit.py
vms/pom/locators/eventsPageLocators.py
vms/pom/pages/basePage.py
vms/pom/pages/eventSignUpPage.py
vms/pom/pages/eventsPage.py
vms/shift/utils.py

Tested Job app
- Move tests from automated testing repo
- Write my own tests
Fixes #702 
- Code
```
python manage.py test job -v 2
```
```
```

Tests for Event app

---

vms/job/models.py
vms/job/tests/test_jobDetails.py
vms/job/tests/test_model.py
vms/job/tests/test_services.py
vms/pom/pages/basePage.py
vms/pom/pages/jobDetailsPage.py

Tested Job app
- Move tests from automated testing repo
- Write my own tests
Fixes #686 
- Code
```
python manage.py test job -v 2
```
```
```

Tests for Job app

---

vms/administrator/tests/test_formFields.py

Test was failing multiple time while testing shift app because of the DOM not being rendered correctly thus needing an explicit wait for DOM render.
Fixes #730 
- Code
```
python manage.py test -v 2
```
and 
```
python manage.py test administrator -v 2
```

Fix error in a test of administrator app

---

vms/event/tests/test_shiftSignUp.py
vms/pom/locators/eventSignUpPageLocators.py
vms/pom/pages/eventSignUpPage.py

Previously I had used get_page() function which is quite fast and caused the DOM to render incorrectly thus making the test unstable. Now I have used click() function via execute script.
Fixes #728 
- Code
```
python manage.py test -v 2
```
and
```
python manage.py test event -v 2
```

Fix error in a test in event app

---

vms/event/tests/test_shiftSignUp.py

search event consisted of 3 checks; both date present, only start, only end. Since for all those 3 checks we were clicking on the same link it created instability and raised StaleElementException. Thus we need to break it in 3 different tests.
Fixes #747 
- Code
This was working fine locally but it creates issues on travis, so we need to check travis logs mainly. Otherwise local testing can be done using
```
python manage.py test event/ -v 2
```

Fix search event test by breaking it into 3 checks

---

vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py

The retention tests of registration app are buggy and unstable thus like retention tests of administrator app thus we need to comment them out and document them. This PR comments them out and the documentation PR documents them.
Fixes #787 
N/A

Comment out retention tests of registration app

---

.travis.yml
requirements.txt
vms/pom/locators/volunteerProfilePageLocators.py
vms/pom/pages/basePage.py
vms/pom/pages/volunteerProfilePage.py
vms/pom/pages/volunteerReportPage.py
vms/pom/pages/volunteerSearchPage.py
vms/volunteer/models.py
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_services.py
vms/volunteer/tests/test_unit.py
vms/volunteer/tests/test_volunteerProfile.py
vms/volunteer/tests/test_volunteerReport.py
vms/volunteer/views.py

Tested shift app
- Write new tests
- Move tests from automated-testing repo.
Closes #735 
- Code
```
python manage.py test volunteer.tests.test_volunteerProfile -v 2
python manage.py test volunteer.tests.test_volunteerReport -v 2
python manage.py test volunteer.tests.test_searchVolunteer -v 2
python manage.py test volunteer.tests.test_services -v 2
```

Testing volunteer app

---

vms/pom/pages/basePage.py
vms/pom/pages/completedShiftsPage.py
vms/pom/pages/manageShiftPage.py
vms/pom/pages/upcomingShiftsPage.py
vms/shift/tests/test_manageVolunteerShift.py
vms/shift/tests/test_services.py
vms/shift/tests/test_shiftDetails.py
vms/shift/tests/test_shiftHours.py
vms/shift/tests/test_unit.py
vms/shift/tests/test_viewVolunteerShift.py
vms/shift/utils.py
vms/shift/views.py
vms/vms/utils.py

Tested shift app
- Write new tests
- Move tests from automated-testing repo.
Closes #720 #725 
- Code
```
python manage.py test shift -v 2
```
```
```

Tests for Shift App

---

vms/event/tests/test_services.py
vms/job/tests/test_services.py
vms/organization/tests/test_services.py
vms/volunteer/tests/test_services.py

This PR increase the invalid id's we are using in tests to test invalid access of objects.
For home and shift app, the changes have been done in their open PRs.
Fixes #809 
- Code
```
python manage.py test -v 2
```

Increase id value for all apps

---

vms/pom/pages/upcomingShiftsPage.py
vms/shift/services.py
vms/shift/tests/test_services.py
vms/shift/tests/test_viewVolunteerShift.py
vms/shift/utils.py
vms/shift/views.py

The upcoming shifts page only shows the present or going shifts.
Fixes #759 
- Code

Upcoming shifts filtered out

---

vms/administrator/tests/test_formFields.py
vms/administrator/tests/test_report.py
vms/administrator/tests/test_settings.py
vms/authentication/tests/test_login.py
vms/event/tests/test_event.py
vms/event/tests/test_shiftSignUp.py
vms/home/tests/test_functional.py
vms/job/tests/test_jobDetails.py
vms/organization/tests/test_organization.py
vms/registration/tests/test_functional_admin.py
vms/registration/tests/test_functional_volunteer.py
vms/shift/tests/test_manageVolunteerShift.py
vms/shift/tests/test_shiftDetails.py
vms/shift/tests/test_shiftHours.py
vms/shift/tests/test_viewVolunteerShift.py
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_volunteerProfile.py
vms/volunteer/tests/test_volunteerReport.py

This PR modifies the existing automated tests to be executed in headless mode by default.
Fixes #803 
- Code
Pull this branch locally and run
```
python manage.py test -v 2
```
you can see that now the browser won't open when tests start.

Execute automated tests in headless mode by default

---

vms/administrator/templates/administrator/report.html
vms/administrator/templates/administrator/view_report.html
vms/administrator/tests/test_report.py
vms/administrator/urls.py
vms/administrator/views.py
vms/pom/locators/administratorReportPageLocators.py
vms/pom/locators/volunteerSearchPageLocators.py
vms/pom/pageUrls.py
vms/pom/pages/administratorReportPage.py
vms/pom/pages/volunteerReportPage.py
vms/pom/pages/volunteerSearchPage.py
vms/shift/admin.py
vms/shift/models.py
vms/shift/services.py
vms/shift/tests/test_services.py
vms/shift/tests/test_shiftHours.py
vms/shift/tests/test_unit.py
vms/shift/utils.py
vms/volunteer/forms.py
vms/volunteer/models.py
vms/volunteer/templates/volunteer/report.html
vms/volunteer/templates/volunteer/search.html
vms/volunteer/templates/volunteer/view_history.html
vms/volunteer/tests/test_searchVolunteer.py
vms/volunteer/tests/test_volunteerReport.py
vms/volunteer/urls.py
vms/volunteer/views.py

The volunteers can create their reports, administrators can confirm them and also they can view the past reports of the volunteers
Fixes #658 
- Code
Volunteer side(volunteer can generate his report):
if the report has already been generated:
Unconfirmed reports(admin can confirm them):
Past reports volunteerwise:

Reporting Functionality added

---

vms/administrator/tests/test_formFields.py
vms/event/tests/test_model.py
vms/pom/locators/eventsPageLocators.py
vms/pom/pages/eventsPage.py
vms/shift/utils.py
vms/volunteer/tests/test_unit.py

Until now only mandatory fields were being saved but we should add checks for other fields too, at least in 1 test. Since these are non-mandatory fields and we'll be shifting to using dicts instead of lists I've used a workaround for now (using length compare) while creating the event. In future we'll need to modify it 
Fixes #752 
- Code
```
python manage.py test event.tests.test_model -v 2
```

Add checks for extra field in model create

---

vms/event/tests/test_model.py
vms/job/tests/test_model.py
vms/volunteer/tests/test_unit.py

This PR includes full clean checks on all fields of event, job and volunteer but we still need to wait for extra checks PR to avoid editing same thing in different PR (utils.py of shift app).
full clean of shift is done in #726 and for admin in #808 
Fixes #797 
- Code
```
python manage.py test event.tests.test_model -v 2
python manage.py test job.tests.test_model -v 2
python manage.py test volunteer.tests.test_unit -v 2
```
**Code/Quality …

Add full clean checks for event, job and volunteer

---

vms/event/forms.py
vms/event/models.py
vms/event/templates/event/create.html
vms/event/templates/event/edit.html
vms/event/tests/test_api.py
vms/event/tests/test_event.py
vms/event/tests/test_model.py
vms/event/views.py
vms/pom/locators/eventsPageLocators.py
vms/pom/pages/eventsPage.py
vms/shift/utils.py

Added description field for events
Fixes #722 
- Code

Added description field in events

---

vms/home/tests/test_functional.py

Earlier the page was giving an error using which the test was asserting results but recent changes in code doesn't give that error hence this check need to be removed.
Fixes #837 
- Code
```
python manage.py test home.tests.test_functional -v 2
```

Fix failing test in home app

---

vms/authentication/templates/registration/password_reset_complete.html
vms/authentication/templates/registration/password_reset_confirm.html
vms/home/templates/home/confirmed_email.html
vms/home/templates/home/email_ask_confirm.html
vms/shift/templates/shift/edit_hours_manager.html
vms/shift/templates/shift/hours_list.html
vms/shift/templates/shift/manage_volunteer_shifts.html

some minor left UI changes
Fixes #841 
- Code
- Outreach

some left UI  changes

---

vms/event/templates/event/list.html
vms/event/views.py

Past events can not be edited.
Fixes #784
- Code
- Outreach

Past events not editable

---

vms/shift/views.py

systerskeeper@gmail.com should be sent the email for editing hours.
- Code
- Outreach

Change admin email id on edit hours

---

docs/Installation_Guide.md

Changes the documentation to  remove the error as mentioned in issue #877.
The following command throws an error because it is missing initialization of an extra field in the model which cant be set as null so changed the command from this so that no error is thrown.
`insert into organization_organization values (1, 'Google');`
`insert into organization_organization values (1, 'Google',1);`
Fixes #877 

Closes #877 Changes in documentation

---

aut_docs/Documented_Failures.md
aut_docs/Installation_Setup.md
vms/vms/settings.py
vms/volunteer/tests/test_volunteerProfile.py

"Permission denied error" were removed by changing access permission to media folders and PyPDF was imported as the test_corrupt_resume_uploaded method required that to run.
Fixes #776 #744 
- Code
Locally
areas

Fixed Resume upload issues

---

aut_docs/Installation_Setup.md

Adds `python manage.py cities_light` command to the installation guide for installation of django cities_light so that we can get a list of countries,state and cities while signing up.
Fixes #888 
No tests required.

Add python manage.py cities_light command to the installation guide

---

requirements.txt

fixes #929
Earlier, Django version 1.11.0 was giving a syntax error when building the project. Updating it to 1.11.17 solves this.
fixes #929 
- Code
- Upgradation of outdated Dependency
This has been tested by me on my local machine when I was building the project.
After updating Django this error went away.

Updates outdate dependency in requirements.txt

---

README.md

Updated the Communicate section of README.md, to link to Zulip channels instead of previous Slack channel. 
Fixes #930 

Updated 'Communicate' section in README.md

---

vms/registration/templates/registration/signup_volunteer.html

Changed the label of country field in Volunteer Signup from City to Country
Fixes #1023 

UI: Changed the label of country field in volunteer signupform

---

docs/Installation_Guide.md

When setting up locally, I realised that some links in Installation Guide are broken may be due to file name change. Therefore, I fix those minor errors.

Fix: Fixed links in Installation Guide

---

vms/vms/templates/vms/base.html

Changed max height of navbar-collapse from 360px to fit content
Fixes #1045 

UI: Made dropdown in admin profile visible
